# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# This re-usable component runs a test

name: test-component

on:
  # run on both call (trigger event) and dispatch (manual)
  workflow_call:
  workflow_dispatch:

jobs:

  test:
    name: test-component
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4 # needed for cache
      - name: set up go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: test
        run: go test -v ./...
