# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# This re-usable component runs a lint

name: lint-component

on:
  # run on both call (trigger event) and dispatch (manual)
  workflow_call:
  workflow_dispatch:

jobs:

  # https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#example-not-requiring-successful-dependent-jobs
  golangci:
    name: lint-component
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5 
        with:
          go-version: '1.22.5'
          cache: false
      - name: golangci-lint
        # https://github.com/golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57 # can use "latest"

